# configuration for feedgen.py

# prefix applied to all URLs in this config file
apiroot: https://api.media.ccc.de/public/

# languages of talks to publish - any events not in this language will be
# filtered out of the feed
languages:
  - eng

genres:
  - educational

# these are items to be added to feed output one time at
# start of file
feedHeader:
  providerName: media.ccc.de
  language: en
  categories:
    - name: Chaos Computer Congresses
      query: congress
      order: most_recent


# list of conference API endpoints to pull for this feed. Each one will be
# expresses as a separate "TV Series" for the Roku backend.
conferences:
  - url:  conferences/35c3
    tags: [ 'congress', '2018', '35C3' ]
    thumbnail: 'https://www.combee.net/roku-ccc/35c3_1920x1080_logo.jpg'
    releaseDate: '2018-12-28'
    shortDescription: >
      The 35th Chaos Communication Congress (35C3) was the 2018 edition
      of the annual four-day conference on technology, society and utopia
      organised by the Chaos Computer Club (CCC) and volunteers.

  # - conferences/34c3
  # - conferences/33c3
  # - conferences/32c3
  # - conferences/31c3
  # - conferences/camp2019
  # - conferences/camp2015

