# configuration for feedgen.py

# prefix applied to all URLs in this config file
apiroot: https://api.media.ccc.de/public/

# languages of talks to publish - any events not in this language will be
# filtered out of the feed
languages:
  - eng

genres:
  - educational

# these are items to be added to feed output one time at
# start of file
feedHeader:
  providerName: media.ccc.de
  language: en
  categories:
    - name: Chaos Computer Congresses
      query: congress
      order: most_recent


# list of conference API endpoints to pull for this feed. Each one will be
# expresses as a separate "TV Series" for the Roku backend.
conferences:
  - url:  conferences/35c3
    tags: [ 'congress', '2018', '35C3' ]
    thumbnail: 'https://www.combee.net/media.ccc.de-on-roku/img/35c3_1920x1080_logo.jpg'
    releaseDate: '2018-12-28'
    shortDescription: >
      The 35th Chaos Communication Congress (35C3) was the 2018 edition
      of the annual four-day conference on technology, society and utopia
      organised by the Chaos Computer Club (CCC) and volunteers.

  - url: conferences/34c3
    tags: [ 'congress', '2017', '34C3' ]
    thumbnail: 'https://www.combee.net/media.ccc.de-on-roku/img/34c3_1920x1080_logo.jpg'
    releaseDate: '2017-12-27'
    shortDescription: >
      The 34th Chaos Communication Congress (34C3) was an annual four-day
      conference on technology, society and utopia. The Congress offers
      lectures and workshops and various events on a multitude of topics
      including (but not limited to) information technology and generally
      a critical-creative attitude towards technology and the discussion
      about the effects of technological advances on society. 

  - url: conferences/33c3
    tags: [ 'congress', '2016', '33C3' ]
    thumbnail: 'https://www.combee.net/media.ccc.de-on-roku/img/33c3_1920x1080_logo.jpg'
    releaseDate: '2016-12-27'
    shortDescription: >
      The 33rd Chaos Communication Congress (33C3) was an annual four-day
      conference on technology, society and utopia. The Congress offers
      lectures and workshops and various events on a multitude of topics
      including (but not limited to) information technology and generally
      a critical-creative attitude towards technology and the discussion
      about the effects of technological advances on society. 

  # - conferences/32c3
  # - conferences/31c3
  # - conferences/camp2019
  # - conferences/camp2015

